from datetime import datetime, timezone
from models import TeamMember


def _photo(name: str) -> str:
    encoded = name.replace(" ", "+")
    return f"https://robohash.org/{encoded}?set=set4&bgset=bg2&size=400x400"


SEED_MEMBERS: list[TeamMember] = [
    TeamMember(
        id="a1b2c3d4-0001-0001-0001-000000000001",
        name="Aryan Velez",
        role="Co-Founder & CEO",
        department="Leadership",
        bio="Robotics systems architect who presented control systems for hyper-redundant arms at IAC 2023. Believes the bottleneck in industrial inspection is access, not intelligence.",
        photo_url=_photo("Aryan Velez"),
        linkedin_url="https://linkedin.com",
        github_url=None,
        is_founder=True,
        joined_date="2023-10",
        skills=["Robotics Systems", "Control Theory", "Fundraising", "Strategy"],
        fun_fact="Once assembled a 6-DOF arm from bicycle parts during a blackout.",
        created_at=datetime(2023, 10, 1, tzinfo=timezone.utc),
    ),
    TeamMember(
        id="a1b2c3d4-0002-0002-0002-000000000002",
        name="Priya Solano",
        role="Co-Founder & CTO",
        department="Leadership",
        bio="Controls and embedded systems specialist who designed the external actuation system from first principles. Has a pathological distrust of off-the-shelf motor drivers.",
        photo_url=_photo("Priya Solano"),
        linkedin_url="https://linkedin.com",
        github_url="https://github.com",
        is_founder=True,
        joined_date="2023-10",
        skills=["Embedded Systems", "Control Systems", "PCB Design", "Firmware"],
        fun_fact="Her first embedded project was a theremin built from a 555 timer at age 14.",
        created_at=datetime(2023, 10, 1, tzinfo=timezone.utc),
    ),
    TeamMember(
        id="a1b2c3d4-0003-0003-0003-000000000003",
        name="Vikram Osei",
        role="Co-Founder & Head of R&D",
        department="Research",
        bio="PhD dropout from computational robotics who would rather build the thing than write about it. Leads AI navigation research and insists every algorithm must run on the arm itself, not in the cloud.",
        photo_url=_photo("Vikram Osei"),
        linkedin_url="https://linkedin.com",
        github_url="https://github.com",
        is_founder=True,
        joined_date="2023-10",
        skills=["Reinforcement Learning", "Computer Vision", "ROS2", "SLAM"],
        fun_fact="Wrote a snake-path planning paper on a 6-hour flight. It was later cited 40 times.",
        created_at=datetime(2023, 10, 1, tzinfo=timezone.utc),
    ),
    TeamMember(
        id="a1b2c3d4-0004-0004-0004-000000000004",
        name="Rohan Deschamps",
        role="Senior Robotics Engineer",
        department="Engineering",
        bio="Specialises in inverse kinematics and real-time path planning for hyper-redundant chains. Responsible for the motion stack on MVP 01. Quietly makes every demo look easy.",
        photo_url=_photo("Rohan Deschamps"),
        linkedin_url="https://linkedin.com",
        github_url="https://github.com",
        is_founder=False,
        joined_date="2024-02",
        skills=["Kinematics", "ROS2", "C++", "Path Planning"],
        fun_fact="Can mentally simulate a 12-DOF arm's workspace. Claims it's just geometry.",
        created_at=datetime(2024, 2, 1, tzinfo=timezone.utc),
    ),
    TeamMember(
        id="a1b2c3d4-0005-0005-0005-000000000005",
        name="Ananya Lindqvist",
        role="Embedded Systems Engineer",
        department="Engineering",
        bio="Writes firmware for the modular end effector system and keeps it under 64 KB. Advocates for bare-metal over RTOS when latency is non-negotiable.",
        photo_url=_photo("Ananya Lindqvist"),
        linkedin_url="https://linkedin.com",
        github_url="https://github.com",
        is_founder=False,
        joined_date="2024-03",
        skills=["STM32", "Bare-Metal C", "CAN Bus", "Sensor Fusion"],
        fun_fact="Her bench has more oscilloscopes than monitors. This is correct.",
        created_at=datetime(2024, 3, 1, tzinfo=timezone.utc),
    ),
    TeamMember(
        id="a1b2c3d4-0006-0006-0006-000000000006",
        name="Siddharth Varga",
        role="Mechanical Design Engineer",
        department="Engineering",
        bio="Designed every structural component of the 3-metre MVP arm with sub-millimetre tolerances. Obsessed with mass optimisation — every gram removed is a gram that doesn't need to be actuated.",
        photo_url=_photo("Siddharth Varga"),
        linkedin_url="https://linkedin.com",
        github_url=None,
        is_founder=False,
        joined_date="2024-04",
        skills=["SolidWorks", "FEA", "DFM", "Composites"],
        fun_fact="Keeps a folder of beautiful stress distribution plots. Purely aesthetic enjoyment.",
        created_at=datetime(2024, 4, 1, tzinfo=timezone.utc),
    ),
    TeamMember(
        id="a1b2c3d4-0007-0007-0007-000000000007",
        name="Meera Achebe",
        role="Software Engineer — Perception",
        department="Engineering",
        bio="Builds the real-time point cloud pipeline and obstacle detection stack that runs on the arm during live inspection. Makes 3D data usable at 30 fps on edge hardware.",
        photo_url=_photo("Meera Achebe"),
        linkedin_url="https://linkedin.com",
        github_url="https://github.com",
        is_founder=False,
        joined_date="2024-06",
        skills=["3D Vision", "PCL", "CUDA", "Python", "C++"],
        fun_fact="Built a real-time 3D scanner for her kitchen once. Mapped every spice jar.",
        created_at=datetime(2024, 6, 1, tzinfo=timezone.utc),
    ),
    TeamMember(
        id="a1b2c3d4-0008-0008-0008-000000000008",
        name="Dr. Kavya Renton",
        role="AI Research Scientist",
        department="Research",
        bio="Develops reinforcement learning policies for navigation inside confined and unstructured environments. Ex-research intern at a major AI lab. Joined Armatrix because the problem is harder.",
        photo_url=_photo("Dr Kavya Renton"),
        linkedin_url="https://linkedin.com",
        github_url="https://github.com",
        is_founder=False,
        joined_date="2024-07",
        skills=["Reinforcement Learning", "PyTorch", "Sim-to-Real Transfer", "Gaussian Processes"],
        fun_fact="Trained a snake navigation policy inside a procedurally generated 'digestive tract' sim.",
        created_at=datetime(2024, 7, 1, tzinfo=timezone.utc),
    ),
    TeamMember(
        id="a1b2c3d4-0009-0009-0009-000000000009",
        name="Aditya Ferreira",
        role="Head of Operations",
        department="Operations",
        bio="Scaled production from a single bench prototype to a 3-metre field-ready arm. Manages vendor relationships, manufacturing partners, and logistics across three states.",
        photo_url=_photo("Aditya Ferreira"),
        linkedin_url="https://linkedin.com",
        github_url=None,
        is_founder=False,
        joined_date="2024-05",
        skills=["Supply Chain", "Vendor Management", "Production Planning", "Procurement"],
        fun_fact="Has a spreadsheet for everything. Including a spreadsheet of his spreadsheets.",
        created_at=datetime(2024, 5, 1, tzinfo=timezone.utc),
    ),
    TeamMember(
        id="a1b2c3d4-0010-0010-0010-000000000010",
        name="Nisha Calderon",
        role="Product Designer",
        department="Design",
        bio="Bridges industrial design and interface design — the arm's physical form and the software operators use to control it. Believes that if the UI is confusing, the arm is broken.",
        photo_url=_photo("Nisha Calderon"),
        linkedin_url="https://linkedin.com",
        github_url=None,
        is_founder=False,
        joined_date="2024-08",
        skills=["Industrial Design", "Figma", "Design Systems", "HRI"],
        fun_fact="Her first prototype was a cardboard snake arm she made during a product sprint. It bent correctly.",
        created_at=datetime(2024, 8, 1, tzinfo=timezone.utc),
    ),
]

# Keyed by id for O(1) lookup and mutation
MEMBERS_DB: dict[str, TeamMember] = {m.id: m for m in SEED_MEMBERS}
